# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    app.markdown:
        class: AppBundle\Utils\Markdown
    app.twig.app_extension:
        class:     AppBundle\Twig\AppExtension
        arguments: ['@app.markdown']
        public:    false
        tags:
            - { name: twig.extension }
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]



